#!/bin/bash

# ***PREAMBLE***
#this script is meant to be ran on only a fresh install of debian 10, but is written
#in such a way that most (maybe all?) features should still work on a setup install

# *** XFCE KEYBOARD SHORTCUTS ***
xfconf-query -c xfce4-keyboard-shortcuts -p /commands/custom/\<Primary\>\<Alt\>t -t string -n -s "xfce4-terminal"
xfconf-query -c xfce4-keyboard-shortcuts -p /commands/custom/Super_L -t string -n -s "xfce4-popup-whiskermenu"

# ***THEME***
#install windows-like dark theme to global themes directory so all users can benefit
sudo tar xzf Qogir-win-dark.tar.gz -C /usr/share/themes/

#tell xfconf to set the window manager to use above theme, then set theme DE-wide
xfconf-query -c xfwm4 -p /general/theme -s "Qogir-win-dark"
xfconf-query -c xsettings -p /Net/ThemeName -s "Qogir-win-dark"


# ***TITLEBAR & MENUBAR***
#tell xfconf to arrange the titlebar buttons in the right order
xfconf-query -c xfwm4 -p /general/button_layout -s "O|HMC"

#hide menu bar in thunar file manager
xfconf-query -c thunar -p /last-menubar-visible -s false


# ***TASKBAR***
#add the stretch repo and update apt package cache if it isn't already present
grep "deb http://deb.debian.org/debian stretch main" /etc/apt/sources.list ||
printf "\n# oldstable repo for stretch packages (added by SkyOS install script)\n\
deb http://deb.debian.org/debian stretch main\n" | sudo tee -a /etc/apt/sources.list > /dev/null
sudo apt update

#install dockbarx dependencies, some of which require above repo
sudo apt install -y gcc zeitgeist python-pip python-dbus python-wnck python-pil python-keybinder python-xlib python-gconf \
valac libgtk2.0-dev build-essential xfce4-panel-dev libxfce4panel-2.0-4 libxfce4panel-2.0-dev libxfconf-0-2 libxfconf-0-dev
#dropped gtk2.0 from above because it is taken as a regex

git clone https://github.com/M7S/dockbarx.git
cd dockbarx && sudo ./setup.py install; cd ..

git clone https://github.com/HugLifeTiZ/xfce4-dockbarx-plugin.git
cd xfce4-dockbarx-plugin

./waf configure --prefix=/usr
./waf build
sudo ./waf install
cd .. && sudo rm -rf xfce4-dockbarx-plugin/ dockbarx/

#set variable with clock plugin id and set time format using it
CLOCKPLUGINID=$(xfconf-query -c xfce4-panel -p /plugins -lv | awk -F / 'NF==3{print $3}' | awk '/clock/{print $1}')
xfconf-query -c xfce4-panel -p /plugins/$CLOCKPLUGINID/digital-format -s "%a %b %d   %H:%M"
xfconf-query -c xfce4-panel -p /plugins/$CLOCKPLUGINID/tooltip-format -s "%A %d %B %Y @ %T"

#taskbar layout customization using xfce4-panel-profiles
sudo apt install intltool
XFPSW="xfce4-panel-profiles-1.0.10"
TBAR="skyos-taskbar-1.0"
wget https://archive.xfce.org/src/apps/xfce4-panel-profiles/1.0/$XFPSW.tar.bz2
bzip2 -d $XFPSW.tar.bz2
tar xvf $XFPSW.tar
cd $XFPSW
./configure
make
sudo make install
cd .. && rm -rf $XFPSW.tar $XFPSW.tar.bz2 $XFPSW
cp skyos-taskbar.txt config.txt
tar cvf $TBAR.tar config.txt
xfce4-panel-profiles load $TBAR.tar && rm $TBAR.tar config.txt

# ***TERMINAL THEMING***
#terminalrc location as a variable to eliminate repetition
XFTERMRCPATH="$HOME/.config/xfce4/terminal/terminalrc"

#update the xfce terminal configuration file to prevent menu bar from showing on new terminals
sed -i "/MiscMenubarDefault=TRUE/c\MiscMenubarDefault=FALSE" $XFTERMRCPATH

#first check if BackgroundMode key exists and create it if not. then set the value
grep '^BackgroundMode=/*' $XFTERMRCPATH > /dev/null || echo "BackgroundMode=" >> $XFTERMRCPATH
sed -i "/BackgroundMode=/c\BackgroundMode=TERMINAL_BACKGROUND_TRANSPARENT" $XFTERMRCPATH

#do the same but for BackgroundDarkness
grep '^BackgroundDarkness=/*' $XFTERMRCPATH > /dev/null || echo "BackgroundDarkness=" >> $XFTERMRCPATH
sed -i "/BackgroundDarkness=/c\BackgroundDarkness=0.95" $XFTERMRCPATH
