#!/bin/bash

# OPTIMALLY THIS SCRIPT SHOULD BE RUN BEFORE WALLPAPERS, BEAR IN MIND ALPHABETICALLY

# tell xfconf to arrange the titlebar buttons in the right order
xfconf-query -c xfwm4 -p /general/button_layout -s "O|HMC"

# hide menu bar in thunar file manager
xfconf-query -c thunar -p /last-menubar-visible -n -t bool -s false

# effectively disable workspaces entirely
xfconf-query -c xfwm4 -p /general/workspace_count -s 1

# disable scrollwheel shade
xfconf-query -c xfwm4 -p /general/mousewheel_rollup -s false
