#!/bin/bash

if ! [[ $SHLVL -gt 2 ]]; then
  echo "This script is not designed to be ran individually. Failing"
  exit 1
fi

# OPTIMALLY THIS SCRIPT SHOULD BE RUN BEFORE WALLPAPERS, BEAR IN MIND ALPHABETICALLY

# tell xfconf to arrange the titlebar buttons in the right order
xfconf-query -c xfwm4 -p /general/button_layout -s "O|HMC"

# hide menu bar in thunar file manager
xfconf-query -c thunar -p /last-menubar-visible -n -t bool -s false

# effectively disable workspaces entirely
xfconf-query -c xfwm4 -p /general/workspace_count -s 1

# disable scrollwheel shade
xfconf-query -c xfwm4 -p /general/mousewheel_rollup -s false

# fix hideously large desktop icon tooltips
xfconf-query -c xfce4-desktop -p /desktop-icons/tooltip-size -n -t int -s 40

# setup picom
sudo dnf install -y picom
mkdir -p $HOME/.config && cp res/desktop/picom.conf "$_"
