#!/bin/bash

if ! [[ $SHLVL -gt 2 ]]; then
  echo "This script is not designed to be ran individually. Please run install.sh instead."
  exit 1
fi

# Make [Y]es the default option when installing packages
CONF_PATH=/etc/dnf/dnf.conf
TEXT='defaultyes=True'

grep -Fqx "$TEXT" $CONF_PATH || echo "$TEXT" >> $CONF_PATH
