#!/bin/bash

if ! [[ $SHLVL -gt 2 ]]; then
  echo "This script is not designed to be ran individually. Failing"
  exit 1
fi

# allow multiple shortcuts to use super key
sudo dnf -y install git gcc make libX11-devel libXtst-devel pkgconfig
gclonecd https://github.com/hanschen/ksuperkey.git
make
sudo make install && cd ..
rm -rf ksuperkey/

# ensure the superkey behavior persists on reboot
cp res/keybindings/superkey.desktop ~/.config/autostart
xfconf-query -c xfce4-keyboard-shortcuts -p "/commands/custom/<Alt>F1" -t string -n -s "xfce4-popup-whiskermenu"

# gnome-like terminal shortcut
xfconf-query -c xfce4-keyboard-shortcuts -p "/commands/custom/<Primary><Alt>t" -t string -n -s "xfce4-terminal"

# windows-like window snapping
xfconf-query -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Shift><Super>Up" -t string -n -s "tile_up_key"
xfconf-query -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Shift><Super>Down" -t string -n -s "hide_window_key"
xfconf-query -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Super>Up" -t string -n -s "maximize_window_key"
xfconf-query -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Super>Down" -t string -n -s "tile_down_key"
xfconf-query -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Super>Left" -t string -n -s "tile_left_key"
xfconf-query -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Super>Right" -t string -n -s "tile_right_key"
