#!/bin/bash

if ! [[ $SHLVL -gt 2 ]]; then
  echo "This script is not designed to be ran individually. Failing"
  exit 1
fi

sudo dnf install -y xfce4-docklike-plugin xfce4-panel-profiles

TBAR=skyos-taskbar
TBAR_CFG=res/taskbar/$TBAR.cfg

# install gtk override stylesheet
mkdir -p $HOME/.config/gtk-3.0 && cp res/taskbar/gtk.css "$_"

# install SkyOS start menu icon
sudo mkdir -p /opt/skyos && sudo cp res/skyos.svg "$_"

cp res/taskbar/whiskermenu-1.rc $HOME/.config/xfce4/panel/
cp $TBAR_CFG config.txt
tar cvf $TBAR.tar config.txt
xfce4-panel-profiles load $TBAR.tar && rm $TBAR.tar config.txt
