#!/bin/bash

if ! [[ $SHLVL -gt 2 ]]; then
  echo "This script is not designed to be ran individually. Please run install.sh instead."
  exit 1
fi

# Ensure the terminal config directory exists
mkdir -p "$HOME/.config/xfce4/terminal"

# Copy terminalrc into that directory
cp $SKYOS_REPO_PATH/res/terminal/terminalrc "$_"


# Install fastfetch
sudo dnf install -y fastfetch

# Ensure the fastfetch config directory exists
mkdir -p "$HOME/.config/fastfetch"

# Copy fastfetch config into that directory
cp $SKYOS_REPO_PATH/res/terminal/config.jsonc "$_"
