#!/bin/bash

#terminalrc location as a variable to eliminate repetition
XFTERM_RC="$HOME/.config/xfce4/terminal/terminalrc"

#ensure the file exists
touch $XFTERM_RC

#update the xfce terminal configuration file to prevent menu bar from showing on new terminals
sed -i "/MiscMenubarDefault=TRUE/c\MiscMenubarDefault=FALSE" $XFTERM_RC

#first check if BackgroundMode key exists and create it if not. then set the value
grep '^BackgroundMode=/*' $XFTERM_RC > /dev/null || echo "BackgroundMode=" >> $XFTERM_RC
sed -i "/BackgroundMode=/c\BackgroundMode=TERMINAL_BACKGROUND_TRANSPARENT" $XFTERM_RC

#do the same but for BackgroundDarkness
grep '^BackgroundDarkness=/*' $XFTERM_RC > /dev/null || echo "BackgroundDarkness=" >> $XFTERM_RC
sed -i "/BackgroundDarkness=/c\BackgroundDarkness=0.95" $XFTERM_RC
