#!/bin/bash

if ! [[ $SHLVL -gt 2 ]]; then
  echo "This script is not designed to be ran individually. Please run install.sh instead."
  exit 1
fi

#terminalrc location as a variable to eliminate repetition
XFTERM_DIR="$HOME/.config/xfce4/terminal"

#ensure the directory exists
mkdir -p $XFTERM_DIR

#ensure the file exists
touch $XFTERM_DIR/terminalrc"

#update the xfce terminal configuration file to prevent menu bar from showing on new terminals
sed -i "/MiscMenubarDefault=TRUE/c\MiscMenubarDefault=FALSE" $XFTERM_RC

#first check if BackgroundMode key exists and create it if not. then set the value
grep '^BackgroundMode=/*' $XFTERM_RC > /dev/null || echo "BackgroundMode=" >> $XFTERM_RC
sed -i "/BackgroundMode=/c\BackgroundMode=TERMINAL_BACKGROUND_TRANSPARENT" $XFTERM_RC

#do the same but for BackgroundDarkness
grep '^BackgroundDarkness=/*' $XFTERM_RC > /dev/null || echo "BackgroundDarkness=" >> $XFTERM_RC
sed -i "/BackgroundDarkness=/c\BackgroundDarkness=0.95" $XFTERM_RC
