#!/bin/bash

if ! [[ $SHLVL -gt 2 ]]; then
  echo "This script is not designed to be ran individually. Please run install.sh instead."
  exit 1
fi

# install wallpapers to global directory
BG_PATH=/usr/share/backgrounds/SkyOS
sudo mkdir -p $BG_PATH
sudo cp $SKYOS_REPO_PATH/res/wallpapers/* $BG_PATH

# set default xfce wallpaper
BG_DEFAULT="$BG_PATH/abstract-evening.png"
xfconf-query --channel xfce4-desktop --list | grep -e '^/backdrop/screen.*/last-image$' | while read PROP_PATH; do
  xfconf-query --channel xfce4-desktop --property $PROP_PATH --set $BG_DEFAULT
done
