#!/bin/bash

if ! [[ $SHLVL -gt 2 ]]; then
  echo "This script is not designed to be ran individually. Please run install.sh instead."
  exit 1
fi

# install wallpapers to global directory
BG_PATH=/usr/share/backgrounds/images

# clear out default fedora wallpapers
sudo rm -rf $BG_PATH/* /usr/share/backgrounds/$(cat /etc/os-release | grep '^VERSION_ID=' | cut -f2 -d=)

# copy custom SkyOS wallpapers into the default wallpaper path
sudo cp $SKYOS_REPO_PATH/res/wallpapers/* $BG_PATH
