#!/bin/bash

if ! [[ $SHLVL -gt 2 ]]; then
  echo "This script is not designed to be ran individually. Please run install.sh instead."
  exit 1
fi

sudo dnf install -y obs-studio

# disable xfce session saving to allow obs autostart
xfconf-query -c xfce4-session -p /general/SaveOnExit -n -t bool -s false

# remove previous sessions
rm -rf ~/.cache/sessions/*

# autostart obs studio
cp res/obs/obs-replay-buffer.desktop ~/.config/autostart/
