#!/bin/bash

if ! [[ $SHLVL -gt 2 ]]; then
  echo "This script is not designed to be ran individually. Please run install.sh instead."
  exit 1
fi

read -p "Enable fusion free? [Y/n]: " RUN; RUN="${RUN:=Y}"
if [ "${RUN^^}" == "Y" ]; then
  enable-fusion free $0
fi

read -p "Enable fusion non-free? [Y/n]: " RUN; RUN="${RUN:=Y}"
if [ "${RUN^^}" == "Y" ]; then
  enable-fusion nonfree $0
fi
