#!/bin/bash

if ! [[ $SHLVL -gt 2 ]]; then
  echo "This script is not designed to be ran individually. Failing"
  exit 1
fi

# ensure rpm fusion nonfree is enabled
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
$SCRIPT_DIR/rpmfusion

sudo dnf install -y steam
