#!/bin/bash

if ! [[ $SHLVL -gt 2 ]]; then
  echo "This script is not designed to be ran individually. Please run install.sh instead."
  exit 1
fi

# Ensure RPM Fusion non-free is enabled
enable-fusion nonfree $0

sudo dnf install -y steam
